### ISSUE TITLE
Return session lifetime with header

### ISSUE THREAD

**Issue by cane-lagerwaard** [deity-io/falcon-magento2-development#110]
Two requests for getting admin token and customer token. Both requests should return lifetime token within header

**Comment by sergy-gzh** [comment]
Its not efficient to feed lifetime information with headers from REST API, cause service logic is completely decoupled from response.
Suggested solution would be to introduce a default value for admin/customer token lifetime (1 hour is the least possible value for it).
So that Falcon can save the token information and request config values.

**Comment by sergy-gzh** [comment]
Related issue in Falcon repo
https://github.com/deity-io/falcon/issues/245
